FROM node:10

WORKDIR /app

COPY package*.json /app/
RUN npm install
COPY . /app

RUN export $(egrep -v '^#' .env | xargs) &&\ 

echo QUEUE_HOST="$QUEUE_HOST\n"\
INTEGRATION_USERNAME="$INTEGRATION_USERNAME\n"\
INTEGRATION_PASSWORD="$INTEGRATION_PASSWORD\n"\
INTEGRATION_GRANT_TYPE="$INTEGRATION_GRANT_TYPE\n"\
INTEGRATION_CLIENT_ID="$INTEGRATION_CLIENT_ID\n"\
INTEGRATION_CLIENT_SECRET="$INTEGRATION_CLIENT_SECRET\n"\ 
INTEGRATION_HOST="$INTEGRATION_HOST\n"\
MONGO_HOST="$MONGO_HOST\n"\
MONGO_USER="$MONGO_USER\n"\
MONGO_PASSWORD="$MONGO_PASSWORD\n"\
MONGO_DB_NAME="$MONGO_DB_NAME\n"\
>> /app/.env

CMD node src/index.js

EXPOSE "$PORT"

